[package]
name = "i3status-custom-pim"
version = "0.1.0"
authors = ["Martin Bley <martin@mb-oss.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
